services:
  api:
    build:
      context: .
      dockerfile: SocialApp.Api/Dockerfile
    environment:
      - ConnectionStrings__SocialAppDb=Server=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - TelegramBotApiKey=${TELEGRAM_BOT_API_KEY}
      - CloudStorageConfig__User=${MINIO_ACCESS_KEY}
      - CloudStorageConfig__Password=${MINIO_SECRET_KEY}
      - CloudStorageConfig__Endpoint=${MINIO_ENDPOINT}
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:8080"
    networks:
      - network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network
    profiles: [ "infra" ]
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "1234:80"
    networks:
      - network
    depends_on:
      - db
    profiles: [ "infra" ]
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    networks:
      - network
    profiles: [ "infra" ]

networks:
  network:
    driver: bridge

volumes:
  pgdata:
  minio_data:
