name: Build and Deploy Docker Compose  

on:  
  push:  
    branches:  
      - main 
      
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v3


    - name: Docker Compose Down (clean state)
      run: |
        docker-compose down || true
        docker system prune -af

    - name: Build and Start Containers
      run: docker-compose up -d 

    - name: Wait for DB to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        sleep 15

    - name: Run .NET Tests (if any)
      run: dotnet test

    - name: Stop and Clean Up
      run: docker-compose down
      
    env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_EMAIL: ${{ secrets.POSTGRES_EMAIL }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          DOCKER_BUILDKIT: 1
