name: Build and Deploy Docker Compose  

on:  
  push:  
    branches:  
      - main 
      
name: Docker Compose Build and Deploy

on:  
  push:  
    branches:  
      - main 
      
jobs:  
  build:  
    runs-on: self-hosted 

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Build and Start Services  
        run: |
          docker-compose down
          docker system prune -af --volumes
          docker-compose up -d --build

      - name: Verify containers
        run: |
          docker ps -a
          docker-compose logs
      
    env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_EMAIL: ${{ secrets.POSTGRES_EMAIL }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          DOCKER_BUILDKIT: "0"
          COMPOSE_DOCKER_CLI_BUILD: "0"
